all:
  hosts:
    nginx:
  children:
    manager:
      hosts:
        project:
    workers:
      hosts:
        w1:
        w2:
  vars:
       ansible_user: golde
    ansible_ssh_private_key_file: "~/.ssh/ansible_id_rsa"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: jenkins
    ansible_ssh_private_key_file: "~/jenkins/.ssh/ansible_id_rsa"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    docker_users: 
      - username: jenkins
      - username: golde

