- name: install proxy nginx
    apt:
      name: nginx
      state: present
      update_cache: true

  - name: Copy nginx conf
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    register: nginx_config

  - name: Restart nginx if needed
    service:
      name: nginx
      state: restarted
    when: nginx_config.changed == true