- name: Init A New Swarm With Default Parameters
  become: true
  community.docker.docker_swarm:
    state: present
  register: swarm_info
- name: print swarm info
  debug:
    msg: "{{ swarm_info }}"