---
# tasks file for manager
- name: 'Init A New Swarm' 
  become: true
  community.docker.docker_swarm:
    state: present
  register: swarm_info
- name: Print Swarm Info
  debug:
    msg: "{{ swarm_info }}"