version: "3.8"
services:
  service1_frontend:
    container_name: service1_frontend
    image: omard786/service1_frontend:latest
    build: ./service1_frontend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
  service2_letters:
    container_name: service2_letters
    image: omard786/service2_letters:latest
    build: ./service2_letters
    ports:
    -   target: 5002
        protocol: tcp
  service-three:
    container_name: service3_numbers
    image: omard786/service3_numbers:latest
    build: ./service3_numbers
    ports:
    - target: 5003
      protocol: tcp
  service-four:
    container_name: service4_comb
    image: omard786/service4_comb:latest
    build: ./service4_comb
    ports:
    -   target: 5004
        protocol: tcp
  