pipeline{
        agent any
        environment{
            DATABASE_URI = credentials("DATABASE_URI")
        }
        stages{
            stage('Test'){
                steps{
                    dir("micro-services"){
                    sh "test.sh"  
                    }

                    }
                }
            stage('Build'){
                steps{
                    dir("micro-services"){
                    sh "docker-compose build" 
                    }

                    }
                }
            stage('Tag & Push Image'){
                steps{
                    sh 'docker ps && docker images'
                    sh 'docker-compose push'
                    }
 
                    }
                }
            stage('Swarm'){
                steps{
                    sh '-i inventory.yaml playbook.yaml'
                    sh "cd /home/jenkins/.local/bin/ansible-playbook -i inventory.yaml playbook.yaml"  
                    }
            
                }
            }
            stage('Deploy App'){
                steps{
                    dir("micro-services"){
                    sh "bash deploy.sh"
                    }

                }
            }
        }
}