pipeline{
        agent any
        environment{
            DATABASE_URI = credentials("DATABASE_URI")
        }
        stages{
            // stage('Test'){
            //     steps{
            //         dir("micro-services"){
            //         sh "bash test.sh"  
            //         }

            //         }
            //     }
            stage('Build'){
                steps{
                    dir("micro-services"){
                    sh "docker-compose build" 
                    }

                    }
                }
            stage('Tag & Push Image'){
                steps{
                    dir("micro-services"){
                    sh 'docker-compose push'
                    }
 
                    }
                }
            stage('Swarm'){
                steps{
                    dir("micro-services/ansible"){
                    sh "/home/jenkins/.local/bin/ansible-playbook -i inventory.yaml playbook.yaml"  
                    }
            
                }
            }
            stage('Deploy App'){
                steps{
                    dir("micro-services"){
                    sh "bash deploy.sh"
                    }

                }
            }
        }
}